const fs = require('fs')
const path = require('path')
const { Source } = require('@storyboard-fm/little-media-box')
const Wavecore = require('..')

const source = fs.readFileSync(path.join(__dirname, '..', 'test', 'test.wav'))
async function main() {
  const w = new Wavecore({ source })
  console.log(w.core)
  console.log('appending to hypercore...')
  await w.open({loadSamples:true})
  console.log('done', w.core)
  console.log('lets cut it down to 12 sec or so')
  await w.truncate(15)
  await w.core.update()
  console.log('done')
  console.log('the hypercore is smaller now', w.core)
  console.log('he is going to end on the sentence "I HATE THIS."')
  return w.play()
}
main()
