const fs = require('fs')
const path = require('path')
const WavecoreSox = require('../sox')

const source = fs.readFileSync(path.join(__dirname, '..', 'test', 'test.wav'))
async function main() {
  const w = new WavecoreSox({ source })
  console.log(w)
  console.log('appending to hypercore...')
  await w.open()
  console.log('done')
  console.log('lets cut it down to 12 sec or so')
  await w.truncate(15)
  await w.update()
  console.log('done')
  console.log('the hypercore is smaller now', w.length)
  console.log('he is going to end on the sentence "I HATE THIS."')
  return w.play()
}
main()
